spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todos
    username: root
    password: Nditec1984#
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    